spring.application.name=backend-finalproject
spring.datasource.url=jdbc:mysql://localhost:3306/jwtrole_s59
spring.datasource.username=root
spring.datasource.password=Tanuja@7172
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=VGhpc0lzQVNlY3JldEtleUZvckp3dFRva2VuR2VuZXJhdGlvbjEyMzQ1Njc4OTAxMjM0NTY3ODkw
jwt.expiration=86400000
app.cors.allowed-origin=http://localhost:5173